### ISSUE TITLE
exe packaged by yao-pkg changed Intl.DateTimeFormat output on windows 

### ISSUE THREAD

**Issue by armgong** [yao-pkg/pkg#101]
### What version of pkg are you using?

5.15.0

### What version of Node.js are you using?

v20.18.0

### What operating system are you using?

windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node20-win-x64  node18-win-x64 

### Describe the Bug

the packaged exe file output wrong format datetime string.
**why this happend , still no any idea!!!**
before package run on console , the output are
~~~
# node index.js
2024/10/10 20:32:34
~~~
run the  packaged exe , the output are
~~~
 test-yao.exe
2024-10-10 20 ├Minute: 34┤ ├Second: 9┤
~~~

### Expected Behavior

output the same as run on console 

### To Reproduce

there is code : 
index.js
~~~
const date = new Date(Date.UTC(2020, 11, 20, 3, 23, 16, 738));
const dateTimeFormatter = new Intl.DateTimeFormat("zh-CN", {
    year: 'numeric',
    hour: 'numeric',
    minute: 'numeric',
    second: 'numeric',
    day: '2-digit',
    month: '2-digit',
});
console.log(dateTimeFormatter.format(Date.now()));
~~~
and  the package.json
~~~
{
  "name": "test-yao",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",  
  "bin": {
    "test-yao": "index.js"
  },
  "pkg": {    
    "targets": [
      "node20-win-x64"
    ]
  }
}
~~~
first run on windows cmd console , its output ar
~~~
Administrator@WIN-Z230 d:\src\test-yao
# node index.js
2024/10/10 20:32:34
~~~
then package it with yao-pkg 5.15.0 
~~~
pkg . --public -C gzip -t node20-win-x64 -o test-yao.exe
~~~
run the  test-yao.exe , the output is 
~~~
 test-yao.exe
2024-10-10 20 ├Minute: 34┤ ├Second: 9┤
~~~

**Comment by armgong** [comment]
![{927B8A69-0DE4-4C27-BEA9-FEC66257FB8C}](https://github.com/user-attachments/assets/6111fca5-531c-4eae-9e01-e09a79e711df)

**Comment by robertsLando** [comment]
reason is that patches are using [small icu](https://github.com/yao-pkg/pkg-fetch/blob/e436d74e4cdfdd8cd4004b672c9d0c3d0e78abc0/lib/build.ts#L71) so Initl may behave different than expected. Reason behind this choice is to keep binary size small

**Comment by armgong** [comment]
maybe this issue is not relate to icu? 
the orgin pkg with 18.15.0 packaged exefile output is correct

**Comment by robertsLando** [comment]
> the orgin pkg with 18.15.0 packaged exefile output is correct, and its size is 39.9 MB , seems it also use small icu?

Based on the logs you provided I don't see it is working even on node 18 https://github.com/yao-pkg/pkg/issues/101#issuecomment-2405026571

The last time we built node 16 has been long time ago so maybe the build changed. I should check the commits history

**Comment by armgong** [comment]
Did more test today，the result is strange, confusing now.

**the origin pkg wiht node18.5.0 , DateTimeFormat is  "zh-CN" or undefined**
~~~
const date = new Date(Date.UTC(2020, 11, 20, 3, 23, 16, 738));
const dateTimeFormatter = new Intl.DateTimeFormat("zh-CN", {
    year: 'numeric',
    hour: 'numeric',
    minute: 'numeric',
    second: 'numeric',
    day: '2-digit',
    month: '2-digit',
    hour12:false,
});
console.log(dateTimeFormatter.format(Date.now()));
~~~
both output is correct 
~~~~
C:\src>cd test-pkg

C:\src\test-pkg>node index.js
2024/10/11 08:30:29

C:\src\test-pkg>pkg . --public -C gzip -t node18-win-x64 -o test18.exe
> pkg@5.8.1
compression:  GZip
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v18.5.0-win-x64             [====================] 100%

C:\src\test-pkg>test18.exe
2024-10-11 8:31:17
~~~~
**the origin pkg wiht node18.20.4 , DateTimeFormat is  "zh-CN" or undefined are wrong**
but when change  DateTimeFormat is  "en-US"
~~~
# test-yao-18.exe
10/11/2024, 8:43:31 AM
~~~

**Comment by robertsLando** [comment]
> I suggest you to give a try packaging the app with: [npmjs.com/package/full-icu](https://www.npmjs.com/package/full-icu) module listed on package.json

**Comment by armgong** [comment]
> > I suggest you to give a try packaging the app with: [npmjs.com/package/full-icu](https://www.npmjs.com/package/full-icu) module listed on package.json
will try it, thanks.
