### ISSUE TITLE
What is difference from official (vercel/pkg) ?

### ISSUE THREAD

**Issue by damartripamungkas** [yao-pkg/pkg#11]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

20.3.1

### What operating system are you using?

macOs, Windows, Linux

### What CPU architecture are you using?

x64

### What Node versions, OSs and CPU architectures are you building for?

node18

### Describe the Bug

What is difference from official (vercel/pkg) ?

### Expected Behavior

What is difference from official (vercel/pkg) ?

### To Reproduce

What is difference from official (vercel/pkg) ?

**Comment by robertsLando** [comment]
Just that this is maintained and that is not

**Comment by damartripamungkas** [comment]
> Just that this is maintained and that is not

please save the changes made by this fork in README.md

**Comment by robertsLando** [comment]
There is a changelog
