### ISSUE TITLE
Linux executable does nothing when launched

### ISSUE THREAD

**Issue by PunishedHideo** [yao-pkg/pkg#120]
### What version of pkg are you using?

6.0.0

### What version of Node.js are you using?

22.11.0

### What operating system are you using?

Ubuntu 22.04.2

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node22-linux-x64

### Describe the Bug

Building with default pkg instruction, .exe for windows works perfectly, but the linux executable just not working, it starts for 1 second, then closes. No errors, nothing

### Expected Behavior

Should work

### To Reproduce

I do

```
chmod +x ExecutableName
./ExecutableName
```

Executable should match everything

**Comment by robertsLando** [comment]
Does it works when using node 20?

**Comment by PunishedHideo** [comment]
> Does it works when using node 20?

Yes, I already figured that out. It seems like ubuntu doesn't like working with node of versions 22 at all it seems. Issue solved.

**Comment by thesunlover** [comment]
@PunishedHideo could you please share how this issue was resolved for Node.js v22 ? Help appreciated. thanks

**Comment by PunishedHideo** [comment]
> [@PunishedHideo](https://github.com/PunishedHideo) could you please share how this issue was resolved for Node.js v22 ? Help appreciated. thanks

Switched from v22 to v20 and exe's started working correctly

**Comment by kkirby** [comment]
I actually had this issue with v22 for Windows. Using v20 worked fine for me in Windows. Not sure what's going on. :-\
