### ISSUE TITLE
NODE_OPTIONS environment variable not work

### ISSUE THREAD

**Issue by cage1618** [yao-pkg/pkg#20]
### What version of pkg are you using?

5.11.1

### What version of Node.js are you using?

20.10.0

### What operating system are you using?

windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node20

### Describe the Bug

How can I dynamically set the environment variable '--max-old-space-size' during runtime, for example using the command 
```
NODE_OPTIONS=--max-old-space-size=8192 ./hello.exe
```
Currently, this approach is not taking effect.

Using `--options=max-old-space-size=8192` is not working; the resulting package has a fixed 'max-old-space-size' of 8192 during runtime.

### Expected Behavior

support dynamic pass NODE_OPTIONS to runtime.

### To Reproduce

NODE_OPTIONS=--max-old-space-size=8192 ./hello.exe

**Comment by robertsLando** [comment]
Setting env vars on windows doesn't work like that: https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows

**Comment by cage1618** [comment]
I use tauri build a cross platform application, I want to dynamic pass max-old-space-size by NODE_OPTION to Command.sidecar env option, how can I do this?

**Comment by kayahr** [comment]
Same problem here. Need to increase the heap size but NODE_OPTIONS is ignored when application is packaged into binary. It only works by hard coding it with `--options max-old-space-size=4096` parameter when calling `pkg`. Would be nice to be able to configure it during runtime.

**Comment by konovalovsergey** [comment]
As mentioned here https://github.com/vercel/pkg/issues/447#issuecomment-1642008116, NODE_OPTIONS is disabled because pkg-fetch enables --without-node-options flag [here](https://github.com/yao-pkg/pkg-fetch/blob/33afe2af5a5d49061836c08fe3bdf38c8923826d/lib/build.ts#L59)

**Comment by max-leuthaeuser** [comment]
Since yao-pkg forked it (https://github.com/yao-pkg/pkg-fetch) are there any plans to remove this restriction, i.e., remove https://github.com/yao-pkg/pkg-fetch/blob/main/lib/build.ts#L60?
Are there any reasonable objections?

**Comment by max-leuthaeuser** [comment]
An explicit override would be an option. It should be the default behaviour (for security).
But when the resulting binary is run in an controlled environment (I run such a binary as part of a parser/compiler toolchain where the memory requirements may need to be adjusted at runtime) folks may want to adjust NODE_OPTIONS.

**Comment by max-leuthaeuser** [comment]
> I think making it a build-time override and printing a warning would be fine, or alternatively adding a new env var for max-old-space-size because that seems to be the primary use case

Yeah, that would be great.

**Comment by robertsLando** [comment]
@max-leuthaeuser PR? I think the latter suggestion about max-old-space size would be a good addition
