### ISSUE TITLE
Error: No native build was found for platform=linux

### ISSUE THREAD

**Issue by LMJayasundara** [yao-pkg/pkg#61]
### What version of pkg are you using?

5.10.0

### What version of Node.js are you using?

v16.20.2

### What operating system are you using?

Linux

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-linuxstatic-armv7

### Describe the Bug

I am trying to build the code with serialport lib i get an errror. i am using linux machine for build the code to armv7l target machine. when i build code without serialport its work perfect. how i solve it

Build machine
![1](https://github.com/yao-pkg/pkg/assets/47645312/38acad79-fca2-43da-b539-407dc18f77c4)

Target machine
![2](https://github.com/yao-pkg/pkg/assets/47645312/3b2150c2-da21-40bb-8f5e-3ac62d9deba5)

Package.json

```
{
  "name": "gbt_charger",
  "version": "1.0.0",
  "description": "",
  "main": "base.js",
  "bin": "base.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "pkg": {
    "assets": [
      "/usr/lib/node_modules/serialport/node_modules/@serialport/bindings-cpp/**/*"
    ]
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ajv": "^8.12.0",
    "ajv-formats": "^2.1.1",
    "easy-crc": "^1.1.0",
    "hex2dec": "^1.1.2",
    "uuid": "^9.0.1",
    "winston": "^3.11.0",
    "winston-daily-rotate-file": "^5.0.0",
    "ws": "^8.14.2",
    "xstate": "^4.38.2"
  }
}
```

in code i import lib as:
```
// some module import from current dir nodemodules 
const { createMachine, interpret, assign, actions } = require('xstate');

// some module import from another file path installed nodemodules folder (like global)
const { open } = require('/usr/lib/node_modules/lmdb');
const { SerialPort } = require('/usr/lib/node_modules/serialport');
const { ByteLengthParser } = require('/usr/lib/node_modules/@serialport/parser-byte-length');
```
but i got error every time shown in Traget machine png

### Expected Behavior

_

### To Reproduce

_

**Comment by LMJayasundara** [comment]
got same error with compile warning
![3](https://github.com/yao-pkg/pkg/assets/47645312/599e59cc-e76e-4dcb-8ea1-720e1c81ed7e)

**Comment by LMJayasundara** [comment]
What do you mean pass

**Comment by robertsLando** [comment]
is package.json inside `/home/ubuntu/gbt/code`?

**Comment by LMJayasundara** [comment]
I run it and get same error message i send you

**Comment by robertsLando** [comment]
I have a feel the problem here is that you are not running the command from inside the package.json folder, could you try to do so? also remember to change the last path with `.`

**Comment by LMJayasundara** [comment]
Yes i run command with outside. Ok, I will try and let you know
