### ISSUE TITLE
Library not loaded: @loader_path/libpixman-1.0.42.2.dylib

### ISSUE THREAD

**Issue by winjeysong** [yao-pkg/pkg#71]
### What version of pkg are you using?

5.12.0

### What version of Node.js are you using?

18.0.0

### What operating system are you using?

macOS

### What CPU architecture are you using?

Apple M1

### What Node versions, OSs and CPU architectures are you building for?

node18-macos-x64

### Describe the Bug

Thanks for maintaining this project! I got a problem when making executable with [`canvas`](https://github.com/Automattic/node-canvas):

<img width="600" src="https://github.com/yao-pkg/pkg/assets/22495161/c2f22817-28a6-434a-a496-f7248da4421c">

 I found a related issue: https://github.com/vercel/pkg/issues/1135, but it seems still not fixed on macos...

### Expected Behavior

make executable with [`canvas`](https://github.com/Automattic/node-canvas)

### To Reproduce

reproduce repo here: https://github.com/winjeysong/pkg-canvas-test.
after cloning, run scripts below and you will see the error message I've mentioned above.
```
pnpm i
pnpm make-bin
pnpm run-bin
```

**Comment by robertsLando** [comment]
add missing lib to assets

**Comment by winjeysong** [comment]
<img width="445" src="https://github.com/yao-pkg/pkg/assets/22495161/7574f55b-13f8-4223-828e-540924fb19a7">

`assets` already set in `package.json`, but useless... 😭

**Comment by robertsLando** [comment]
Try with `node_modules/canvas/**/*`

**Comment by winjeysong** [comment]
> Try with `node_modules/canvas/**/*`

still error...
It seems `pkg` only copies `canvas.node` to cache dir, but ignores all other `.dylib` files

<img width="400" style="vertical-align:top" src="https://github.com/yao-pkg/pkg/assets/22495161/7e7c5060-80ba-4b21-95f5-480b0c7060a3">

<img width="400" style="vertical-align:top" src="https://github.com/yao-pkg/pkg/assets/22495161/64b9d522-7009-4b93-86db-cd985fee2ad6">

**Comment by robertsLando** [comment]
The code that handles the copy of that folder is this: https://github.com/yao-pkg/pkg/blob/main/prelude/bootstrap.js#L2199

Try to debug it yourself (maybe better if you create a minimal repo that only imports canvas)

**Comment by winjeysong** [comment]
Thank you for your rapid response.
I'm debugging now, and I'll open a PR asap.

**Comment by winjeysong** [comment]
After debugging, I find that running `pkg src/index.js --output dist/bin --targets node18-macos-x64 --compress GZip` will not include `packageJSON.pkg` config.
And I reread the doc carefully, It says:
> Just be sure to call pkg package.json or pkg . to make use of package.json configuration.

I changed `package.json` and it works now.
<img width="600" src="https://github.com/yao-pkg/pkg/assets/22495161/2c48c4d0-d897-43ef-b83b-0665cc038cc4">

It would be nice if the `packageJSON.pkg` config merges with command line config.

**Comment by robertsLando** [comment]
Would you like to submit a PR? Glad you fixed your issue anyway :)
